---
version: '3'
services:
  packer:
    build:
      context: ./packer
    dns_search: home.local
    dns:
      - 192.168.200.1
    volumes:
      - ./workspace:/packer
      - ./ssh:/root/.ssh:ro
    entrypoint: bash /packer/start.sh
