#!/usr/bin/ansible-playbook -i localhost,
---
- name: Playbook to get installer files
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    iso_folders:
      - centos/8-stream
      - debian/bullseye
      - ubuntu/focal
      - ubuntu/jammy

    iso_files:
      - folder: centos/8-stream
        url: http://isoredirect.centos.org/centos/8-stream/isos/x86_64/CentOS-Stream-8-x86_64-latest-boot.iso

      - folder: debian/bullseye
        url: https://deb.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux

      - folder: debian/bullseye
        url: https://deb.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
 
      - folder: ubuntu/focal
        url: http://releases.ubuntu.com/focal/ubuntu-20.04.4-live-server-amd64.iso

      - folder: ubuntu/jammy
        url: https://releases.ubuntu.com/jammy/ubuntu-22.04.1-live-server-amd64.iso
 
  tasks:
    - name: Create installer folders
      file:
        path: '{{ iso_folder }}'
        state: directory
      loop: '{{ iso_folders }}'
      loop_control:
        loop_var: iso_folder

    - name: Get installer files
      get_url:
        url: '{{ iso_file.url }}'
        dest: '{{ playbook_dir }}/{{ iso_file.folder }}/{{ iso_file.url | basename }}'
        force: no
      loop: '{{ iso_files }}'
      loop_control:
        loop_var: iso_file
