#!/usr/bin/ansible-playbook -i localhost,
---
- name: Mount ISO files
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    iso_state: mounted # can be overridden by passing in -e iso_state=<value> to playbook

  tasks:
    - name: Run command
      mount:
        path: '{{ iso_file | dirname }}/iso_contents'
        src: '{{ iso_file }}'
        fstype: iso9660
        state: '{{ iso_state }}'
      with_lines:
        - "find {{ playbook_dir }} -type f -name '*.iso'"
      loop_control:
        loop_var: iso_file
