#!/usr/bin/ansible-playbook -i localhost,
#
# Description:  Mounts ISO files found in sub-directories to a local iso_contents folder.
# Passing `-e iso_state=unmounted` will unmount the ISO files.
#
---
- name: Mount ISO files
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    iso_state: mounted # can be overridden by passing in -e iso_state=<value> to playbook

  tasks:
    - name: Run command to mount ISO file to local iso_contents folder
      mount:
        path: '{{ iso_file | dirname }}/iso_contents'
        src: '{{ iso_file }}'
        fstype: iso9660
        state: '{{ iso_state }}'
      with_lines:
        - "find {{ playbook_dir }} -type f -name '*.iso'"
      loop_control:
        loop_var: iso_file
